### ISSUE TITLE
Build as meson subproject fails to find picolibc.h

### ISSUE THREAD

**Issue by aewag** [picolibc/picolibc#108]
I want to embed the picolibc lib as a meson subproject. Meson does find picolibc as subprojects, but building fails:

```
|Configuring picolibc.h using configuration
|Build targets in project: 35
|Subproject picolibc finished.

../meson.build:23:0: ERROR: Requested variable "picolibc_dep" not found.
```

In the top meson.build I integrated picolibc as a subproject:
```
picolibc_proj = subproject('picolibc')
picolibc_dep = picolibc_proj.get_variable('picolibc_dep')
```
It seemed that the variable is not defined I looked into the meson.build and it seems that `enable_multilib` is set and therefore the variable is unknown.

Disabling the check for `enable_multilib` lets meson top project find the variable, but then it fails to find `picolibc.h` while compiling the files.

**Comment by keith-packard** [comment]
Ah, I sorted it out -- I added an explicit '-include', 'picolibc.h' to the internal c_args so that every file would be sure to have these definitions available (a few asm files were missing this, in particular). A couple of options to fix this:

 1. Fix the source code to make sure picolibc.h is included everywhere it is needed and remove it from the default c_args.
 2. Split that part of c_args out to a separate var so that wrapping projects don't have that in their compile commmand
 3. Fix the path used to find picolibc.h so that it is relative to the picolibc directory instead of the project root.

**Comment by keith-packard** [comment]
I've created a sample application that uses picolibc as a subproject to explore this issue. I think the key is to not use the c_args in your project -- the only thing in the picolibc c_args is this --include option.

Check out https://github.com/picolibc/pico-hello and see if that helps you get this working.

**Comment by aewag** [comment]
Thank you! That example code really helped and was a good starter for better understanding.
