### ISSUE TITLE
test: ungetc fails with -Dposix-console=false

### ISSUE THREAD

**Issue by yashi** [picolibc/picolibc#179]
This is a question rather than bug report.

While working on #177, I've noticed that some tests are using `stdin`, `stdout`, or `stderr` even when `-Dposix-console=false`.

`meson_options.txt` says for the option:

> Use POSIX I/O for stdin/stdout/stderr

But what the option actually do is to leave `newlib/libc/tinystdio/posixiob.c` out from compilation.  The file defines and replaces `stdin`, `stdout`, and `stderr` from the platform.  So, if you don't include `posixiob.c`, you are actually using the platform stdio.  AFAICS, `test/ungetc` is the only one failing in the tests.  But many functions are accessing `stream->flag`, or some other member which doesn't exist in other `FILE`.

Or, because the test is actually for both tinystdio and newlib stdio, we keep as is?  I noticed the `tests_enable_posix_io` option.  Maybe we can just move `ungetc` from `plain_tests` to `posix-io`?

If someone gives me a direction, I can prepare for a PR (if we need it)

**Comment by keith-packard** [comment]
> A right way is that an oslib should have a proper console support and no need to link against dummyhost.

I usually have the application provide stdin/stdout/stderr in object files provided to the linker as those can then use application-specific console I/O functions. The oslib implementations are mostly meant to provide a way to link stand-alone tests and early bring-up code for new processors. Once you've got an RTOS running, you'd want to create your own version of stdin/stdout/stderr, not use one of the oslibs provided by picolibc. I suppose one could create a zephyr oslib that provided stdin/stdout/stderr using and pass that using the --oslib command line parameter though?

**Comment by keith-packard** [comment]
> How about checking whether the current build is a native build or not with [`meson.is_cross_build()`](https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonis_cross_build). If we are native build, we link to `posixiob.c`.

Making it harder to mis-configure the library seems like a good idea, but I'm not sure I understand the reasoning here. The only reason you'd ever build picolibc on a real POSIX system is to test the library; it's otherwise not terribly useful as the underlying system presumably has a full libc available.

We could change the build system so that if the user didn't specify a value for posix-console it would automatically enable it for non-cross builds? That would avoid this particular mis-configuration problem

**Comment by yashi** [comment]
I'm trying to understand the way the current build system is doing things.  My motivation is to understand how and why it does, so that I can learn something from picolibc and port it to Zephyr.  So, it might seems silly to tweak the working meson script just for readability because I'm not achieving anything as an output at the end. (except for cleaner `meson.build`s I hope).

Anyway, I'll post a few PR to, hopefully, clean up `meson.build` in coming days.  Just drop it if you don't like it.

**Comment by keith-packard** [comment]
Much appreciate you review in this area; few people spend time trying to improve developer experience in using this aspect of any project, so getting some comments on how you see the system as you try to create a parallel cmake system is really useful.

**Comment by yashi** [comment]
a quick question:

https://github.com/picolibc/picolibc/blob/4b4a69f42f2e6fa5d6e44607adefe10f38d1b51a/newlib/libc/meson.build#L144

Is there any reason you want to prepend relatively specific deep include directories in front of shallow-dir / broad include like the top-dir or 'newlib/libc/tinystdio'?  IOW, do we have any restriction in the header file search path?

**Comment by keith-packard** [comment]
tinystdio is a special case -- because picolibc includes two complete stdio implementations (at least currently), the related header files can't be placed in the shared include directory, instead they are left in the stdio implementation directory. While building the library, that means placing the stdio source directory in the include search path.
The general plan is to make sure that the include path gets set so that the source code in the library can use the same `#include` directives as application source code using the library. Meson adds a lot of extra paths to the include search list so that headers created during the build process can also be found, independent of where the build system places them.
